name: 'Secret Replace Action'
description: 'Replace yours files by screts'
inputs:
  file:
    description: Template file.
    required: true
  endpoint:
    description: Vualt endpoint
    required: true
  vaultToken:
    description: Vault token
    required: true
  vaultPath:
    description: Api Path
    required: true
  namespace:
    description: Vault namespace
    default: admin
    required: false    
runs:
  using: 'node16'
  main: 'lib/index.js'